DROP DATABASE IF EXISTS UNIVERSIDADE;
CREATE DATABASE IF NOT EXISTS UNIVERSIDADE;
USE UNIVERSIDADE;

CREATE TABLE IF NOT EXISTS PROFESSOR (
	ID_PROFESSOR INT NOT NULL PRIMARY KEY,
	SOBRENOME VARCHAR (25),
	NOME VARCHAR (25),
	PRONTUARIO VARCHAR (20)
);

CREATE TABLE IF NOT EXISTS AREA (
	ID_AREA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR (25)
);

CREATE TABLE IF NOT EXISTS CURSO (
	ID_CURSO INT NOT NULL PRIMARY KEY,
	NOME VARCHAR (25),
	COD_AREA INT,
	FOREIGN KEY (COD_AREA)
		REFERENCES AREA (ID_AREA)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALUNO (
	ID_ALUNO INT NOT NULL PRIMARY KEY,
	NOME VARCHAR (25),
	PRONTUARIO VARCHAR (20),
	COD_CURSO INT,
	FOREIGN KEY (COD_CURSO)
		REFERENCES CURSO (ID_CURSO)
		ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS DISCIPLINA (
    ID_DISCIPLINA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(25);
	DESCRICAO VARCHAR(25);
	COD_CURSO INT,
	COD_PROFESSOR INT,
	ANO DATE,
	FOREIGN KEY (COD_CURSO)
		REFERENCES CURSO (ID_CURSO)
        ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (COD_PROFESSOR)
		REFERENCES PROFESSOR (ID_PROFESSOR)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TURMAS (
	ID_TURMA INT NOT NULL PRIMARY KEY,
	NUM_TURMA INT NOT NULL,
	COD_DISCIPLINA INT,
	COD_ALUNO INT,
	FOREIGN KEY (COD_DISCIPLINA)
		REFERENCES DISCIPLINA (ID_DISCIPLINA)
		ON UPDATE CASCADE ON DELETE CASCADE
	FOREIGN KEY (COD_ALUNO)
		REFERENCES ALUNO (ID_ALUNO)
		ON UPDATE CASCADE ON DELETE CASCADE
);